/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BookRouteImport } from './routes/book'
import { Route as AddStoreRouteImport } from './routes/add-store'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookResultsRouteImport } from './routes/book.results'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AddStoreRoute = AddStoreRouteImport.update({
  id: '/add-store',
  path: '/add-store',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookResultsRoute = BookResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => BookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-store': typeof AddStoreRoute
  '/book': typeof BookRouteWithChildren
  '/community': typeof CommunityRoute
  '/explore': typeof ExploreRoute
  '/products': typeof ProductsRoute
  '/book/results': typeof BookResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-store': typeof AddStoreRoute
  '/book': typeof BookRouteWithChildren
  '/community': typeof CommunityRoute
  '/explore': typeof ExploreRoute
  '/products': typeof ProductsRoute
  '/book/results': typeof BookResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-store': typeof AddStoreRoute
  '/book': typeof BookRouteWithChildren
  '/community': typeof CommunityRoute
  '/explore': typeof ExploreRoute
  '/products': typeof ProductsRoute
  '/book/results': typeof BookResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-store'
    | '/book'
    | '/community'
    | '/explore'
    | '/products'
    | '/book/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-store'
    | '/book'
    | '/community'
    | '/explore'
    | '/products'
    | '/book/results'
  id:
    | '__root__'
    | '/'
    | '/add-store'
    | '/book'
    | '/community'
    | '/explore'
    | '/products'
    | '/book/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddStoreRoute: typeof AddStoreRoute
  BookRoute: typeof BookRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  ExploreRoute: typeof ExploreRoute
  ProductsRoute: typeof ProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-store': {
      id: '/add-store'
      path: '/add-store'
      fullPath: '/add-store'
      preLoaderRoute: typeof AddStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/results': {
      id: '/book/results'
      path: '/results'
      fullPath: '/book/results'
      preLoaderRoute: typeof BookResultsRouteImport
      parentRoute: typeof BookRoute
    }
  }
}

interface BookRouteChildren {
  BookResultsRoute: typeof BookResultsRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookResultsRoute: BookResultsRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddStoreRoute: AddStoreRoute,
  BookRoute: BookRouteWithChildren,
  CommunityRoute: CommunityRoute,
  ExploreRoute: ExploreRoute,
  ProductsRoute: ProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
